# Generated by Django 5.0.6 on 2026-09-28 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=16, verbose_name='ФН')),
                ('fd', models.CharField(max_length=10, verbose_name='ФД')),
                ('fp', models.CharField(max_length=10, verbose_name='ФП')),
                ('purchase_datetime', models.DateTimeField(verbose_name='Дата и время покупки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('reject_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Фото чека')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-purchase_datetime'],
                'indexes': [models.Index(fields=['user', '-purchase_datetime'], name='promo_recei_user_id_2712a4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('fn', 'fd', 'fp'), name='uniq_receipt_fn_fd_fp_active'),
        ),
    ]
